# John The Ripper
- name: John
  tags: john
  become: true
  ansible.builtin.apt:
    name: john

- name: Install john tools
  tags: john
  copy:
    src: "{{ playbook_dir }}/roles/passwords/files/john/"
    dest: "{{ ansible_env.HOME }}/.local/bin/"

- name: Chmod +x *.2john
  tags: john
  ansible.builtin.shell: chmod +x ~/.local/bin/*2john

- name: Hydra
  tags: hydra
  become: true
  ansible.builtin.apt:
    name: hydra