- name: VSCode
  tags: vscode
  become: true
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

# https://github.com/Densaugeo/uploadserver
- name: Uploadserver
  tags: uploadserver
  ansible.builtin.shell: pipx install git+https://github.com/Densaugeo/uploadserver

# https://github.com/bitsadmin/wesng
- name: Wesng
  tags: wesng
  ansible.builtin.shell: |
    pipx install git+https://github.com/bitsadmin/wesng
    pipx inject wesng chardet

- name: Rlwrap
  tags: rlwrap
  become: true
  ansible.builtin.apt:
    name: rlwrap